Repository woorifisa-projects-3rd/Crews-BE-Service, pull requests merged in 2024-12, with the labels that each got.

#59 57 feature agit manage api
  src/main/java/org/crews/controller/AccountController.java
  src/main/java/org/crews/controller/AgitController.java
  src/main/java/org/crews/dto/request/AgitInfoRequest.java
  src/main/java/org/crews/dto/response/AgitInfoResponse.java
  src/main/java/org/crews/dto/response/AgitManageMemberResponse.java
  src/main/java/org/crews/dto/response/AgitManageResponse.java
  src/main/java/org/crews/model/Membership.java
  src/main/java/org/crews/model/constants/AgitRole.java
  src/main/java/org/crews/repository/MemberShipRepository.java
  src/main/java/org/crews/service/AccountService.java
  src/main/java/org/crews/service/AgitService.java
  src/main/java/org/crews/service/CardService.java
  src/main/java/org/crews/service/DuesService.java
  src/main/java/org/crews/service/IntroducingService.java
  src/main/java/org/crews/service/MeetingService.java
Labels: Feature

#61 [feat/#52]: PIN번호 인증 및 feed/meeting 상세조회 오류 수정
  src/main/java/org/crews/controller/MemberController.java
  src/main/java/org/crews/dto/request/MemberRequest.java
  src/main/java/org/crews/dto/request/PinNumberRequest.java
  src/main/java/org/crews/exception/ErrorCode.java
  src/main/java/org/crews/jwt/JWTFilter.java
  src/main/java/org/crews/repository/FeedRepository.java
  src/main/java/org/crews/repository/MeetingRepository.java
  src/main/java/org/crews/service/FeedService.java
  src/main/java/org/crews/service/MeetingService.java
  src/main/java/org/crews/service/MemberService.java
  src/main/java/org/crews/service/MemberServiceImpl.java
Labels: Feature

#67 60 search agits api
  src/main/java/org/crews/config/SecurityConfig.java
  src/main/java/org/crews/controller/AgitController.java
  src/main/java/org/crews/dto/response/AgitSliceResponse.java
  src/main/java/org/crews/dto/response/IntroducingResponse.java
  src/main/java/org/crews/jwt/LoginFilter.java
  src/main/java/org/crews/repository/AgitRepository.java
  src/main/java/org/crews/service/AgitService.java
  src/main/java/org/crews/service/MemberServiceImpl.java
Labels: Feature

#66 [feat/#64]: 모집임박/신규모임 조회 API 생성
  src/main/java/org/crews/config/SecurityConfig.java
  src/main/java/org/crews/controller/AgitController.java
  src/main/java/org/crews/controller/MemberController.java
  src/main/java/org/crews/dto/response/AgitSortResponse.java
  src/main/java/org/crews/model/Agit.java
  src/main/java/org/crews/repository/AgitRepository.java
  src/main/java/org/crews/service/AgitService.java
  src/main/java/org/crews/utils/AuthUtil.java
Labels: Feature

#68 아지트 정모 수정 api 구현
  src/main/java/org/crews/controller/FeedController.java
  src/main/java/org/crews/controller/MeetingController.java
  src/main/java/org/crews/dto/request/MeetingRequest.java
  src/main/java/org/crews/model/Meeting.java
  src/main/java/org/crews/service/MeetingService.java
Labels: Feature

#62 [feat/#56] : 아지트 기록 수정, 삭제, 신고 구현
  src/main/java/org/crews/controller/FeedController.java
  src/main/java/org/crews/controller/ReportController.java
  src/main/java/org/crews/dto/request/ReportRequest.java
  src/main/java/org/crews/dto/response/AgitVaildationResponse.java
  src/main/java/org/crews/dto/response/FeedResponse.java
  src/main/java/org/crews/dto/response/ReportResponse.java
  src/main/java/org/crews/exception/ErrorCode.java
  src/main/java/org/crews/model/Feed.java
  src/main/java/org/crews/model/Report.java
  src/main/java/org/crews/repository/HeartRepository.java
  src/main/java/org/crews/repository/ReportRepository.java
  src/main/java/org/crews/service/FeedService.java
  src/main/java/org/crews/service/ReportService.java
  src/main/java/org/crews/utils/CheckExceptionUtil.java
  src/main/resources/schema.sql
Labels: Feature

#71 [Refactor#60]: Agit_Request_Logic_Refactoring
  src/main/java/org/crews/controller/AgitController.java
  src/main/java/org/crews/dto/request/AgitInfoRequest.java
  src/main/java/org/crews/service/AgitService.java
Labels: Feature

#72 [rename/#70]: dto 오타 수정
  src/main/java/org/crews/dto/response/AgitValidationResponse.java
  src/main/java/org/crews/service/FeedService.java
  src/main/java/org/crews/service/IntroducingService.java
  src/main/java/org/crews/service/MeetingService.java
  src/main/java/org/crews/service/ReportService.java
  src/main/java/org/crews/utils/CheckExceptionUtil.java
Labels: Fix

#77 [Feat#74] Agit_Creation_Get_Address_And_Validate_AgitName
  src/main/java/org/crews/controller/AgitController.java
  src/main/java/org/crews/dto/request/AgitRequest.java
  src/main/java/org/crews/dto/response/AgitNameValidateResponse.java
  src/main/java/org/crews/repository/AgitRepository.java
  src/main/java/org/crews/service/AgitService.java
Labels: Feature

#75 [feat/#69]: 아지트 subject 별로 조회 추가, data slicing for infinite scroll
  src/main/java/org/crews/config/SecurityConfig.java
  src/main/java/org/crews/controller/AgitController.java
  src/main/java/org/crews/dto/core/BalanceInfoResponse.java
  src/main/java/org/crews/dto/response/AgitResponse.java
  src/main/java/org/crews/dto/response/ReportResponse.java
  src/main/java/org/crews/exception/ErrorCode.java
  src/main/java/org/crews/jwt/JWTFilter.java
  src/main/java/org/crews/model/Agit.java
  src/main/java/org/crews/repository/AgitRepository.java
  src/main/java/org/crews/repository/MemberRepository.java
  src/main/java/org/crews/service/AgitService.java
  src/main/java/org/crews/service/FeedService.java
  src/main/java/org/crews/service/IntroducingService.java
  src/main/java/org/crews/service/ReportService.java
  src/main/java/org/crews/utils/CheckExceptionUtil.java
  src/main/resources/data.sql
Labels: Feature

#83 82 card api update
  src/main/java/org/crews/controller/AccountController.java
  src/main/java/org/crews/controller/CardController.java
  src/main/java/org/crews/dto/request/CardRemoveRequest.java
  src/main/java/org/crews/dto/response/CardIssuanceResponse.java
  src/main/java/org/crews/service/AccountService.java
  src/main/java/org/crews/service/CardService.java
  src/main/java/org/crews/service/CustomUserDetailsService.java
  src/main/java/org/crews/utils/MaskedNumber.java
  src/main/resources/schema.sql
Labels: Feature

#93 [feat/#90]: 관리자 API 구현, 유저 벤 컬럼 추가 ,
  src/main/java/org/crews/config/SecurityConfig.java
  src/main/java/org/crews/controller/AdminController.java
  src/main/java/org/crews/dto/response/BanResponse.java
  src/main/java/org/crews/dto/response/ReportedFeedResponse.java
  src/main/java/org/crews/dto/response/ReportedFeedSliceResponse.java
  src/main/java/org/crews/exception/ErrorCode.java
  src/main/java/org/crews/model/Member.java
  src/main/java/org/crews/repository/ReportRepository.java
  src/main/java/org/crews/service/AdminService.java
  src/main/java/org/crews/utils/AuthUtil.java
  src/main/resources/data.sql
  src/main/resources/schema.sql
Labels: Feature

#94 81 payment api
  build.gradle
  src/main/java/org/crews/config/SecurityConfig.java
  src/main/java/org/crews/controller/PaymentController.java
  src/main/java/org/crews/dto/core/TransferResponse.java
  src/main/java/org/crews/dto/request/CardPaymentRequest.java
  src/main/java/org/crews/dto/request/MemberRequest.java
  src/main/java/org/crews/dto/response/PaymentInfoResponse.java
  src/main/java/org/crews/dto/sqs/MessagePayload.java
  src/main/java/org/crews/model/constants/CardName.java
  src/main/java/org/crews/model/constants/PaymentTargetAccount.java
  src/main/java/org/crews/repository/CardRepository.java
  src/main/java/org/crews/repository/MemberShipRepository.java
  src/main/java/org/crews/service/PaymentService.java
  src/main/java/org/crews/service/PaymentServiceImpl.java
  src/main/java/org/crews/utils/QRCodeUtil.java
  src/main/java/org/crews/utils/S3Util.java
  src/main/java/org/crews/utils/SQSUtil.java
  src/test/java/org/crews/CrewsApplicationTests.java
Labels: Feature

#87 86 card update api
  src/main/java/org/crews/controller/AccountController.java
  src/main/java/org/crews/controller/AgitController.java
  src/main/java/org/crews/controller/CardController.java
  src/main/java/org/crews/dto/core/AccountOneResponse.java
  src/main/java/org/crews/dto/request/DuesCallRequest.java
  src/main/java/org/crews/dto/response/AccountV2CrewResponse.java
  src/main/java/org/crews/dto/response/AccountV2PersonalResponse.java
  src/main/java/org/crews/exception/ErrorCode.java
  src/main/java/org/crews/repository/AccountRepository.java
  src/main/java/org/crews/service/AccountService.java
  src/main/java/org/crews/service/AgitService.java
  src/main/java/org/crews/service/CardService.java
  src/main/java/org/crews/service/CommonService.java
  src/main/java/org/crews/service/DuesService.java
Labels: Feature

#80 [feat/#76]: 아지트 권한 관리 구현 및 일부 수정
  build.gradle
  crews.drawio
  src/main/java/org/crews/CrewsApplication.java
  src/main/java/org/crews/controller/AgitController.java
  src/main/java/org/crews/controller/FeedController.java
  src/main/java/org/crews/controller/IntroducingController.java
  src/main/java/org/crews/controller/MeetingController.java
  src/main/java/org/crews/controller/ReportController.java
  src/main/java/org/crews/dto/core/ProductResponse.java
  src/main/java/org/crews/dto/request/AgitAuthorRequest.java
  src/main/java/org/crews/dto/request/CardPaymentRequest.java
  src/main/java/org/crews/dto/request/MeetingRequest.java
  src/main/java/org/crews/dto/response/AccountV2PersonalResponse.java
  src/main/java/org/crews/dto/response/AgitManageResponse.java
  src/main/java/org/crews/dto/response/FeedResponse.java
  src/main/java/org/crews/dto/response/IntroducingResponse.java
  src/main/java/org/crews/dto/response/MeetingResponse.java
  src/main/java/org/crews/dto/response/MembershipResponse.java
  src/main/java/org/crews/exception/ErrorCode.java
  src/main/java/org/crews/model/AccountHistory.java
  src/main/java/org/crews/model/Dues.java
  src/main/java/org/crews/model/Membership.java
  src/main/java/org/crews/repository/MembershipRepository.java
  src/main/java/org/crews/service/AccountService.java
  src/main/java/org/crews/service/AgitService.java
  src/main/java/org/crews/service/CardService.java
  src/main/java/org/crews/service/CommonService.java
  src/main/java/org/crews/service/CustomUserDetailsService.java
  src/main/java/org/crews/service/DuesService.java
  src/main/java/org/crews/service/IntroducingService.java
  src/main/java/org/crews/service/MemberService.java
  src/main/java/org/crews/service/MemberServiceImpl.java
  src/main/java/org/crews/service/MembershipService.java
  src/main/java/org/crews/service/PaymentServiceImpl.java
  src/main/java/org/crews/service/ReportService.java
  src/main/java/org/crews/utils/CheckExceptionUtil.java
  src/main/java/org/crews/utils/DuesCommon.java
  src/main/resources/data.sql
  src/main/resources/schema.sql
  src/test/java/org/crews/service/AccountServiceTest.java
  src/test/java/org/crews/service/AgitServiceTest.java
  src/test/java/org/crews/service/MemberServiceImplTest.java
Labels: Feature

#99 feat: api 수정
  src/main/java/org/crews/controller/CommonController.java
  src/main/java/org/crews/controller/PaymentController.java
  src/main/java/org/crews/exception/ErrorCode.java
  src/main/java/org/crews/repository/MembershipRepository.java
  src/main/java/org/crews/service/AccountService.java
  src/main/java/org/crews/service/CommonService.java
  src/main/java/org/crews/service/CoreService.java
  src/main/java/org/crews/service/DuesService.java
  src/main/java/org/crews/utils/NumberFormatter.java
Labels: Feature

#103 feat: member 가입시 nickName필드 삭제
  src/main/java/org/crews/dto/request/MemberRequest.java
Labels: Feature

#104 hotfix: member nickname필드 삭제
  src/main/java/org/crews/model/Member.java
Labels: Bug

#105 [feat/#76]: 아지트 관리 api 추가, 암호화 안된 데이터를 복호화할 때 그냥 원래 값 출력하는 메서드 추가(삭제 가능)
  src/main/java/org/crews/controller/AgitController.java
  src/main/java/org/crews/repository/MembershipRepository.java
  src/main/java/org/crews/service/AgitService.java
  src/main/java/org/crews/utils/AESUtil.java
Labels: Feature
